# Generated by Django 2.2.3 on 2019-07-23 10:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0003_property_completion_year'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(blank=True, max_length=30, null=True)),
                ('lastname', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('national_id', models.CharField(blank=True, max_length=8, null=True, validators=[django.core.validators.RegexValidator(message="National id must be entered in the format: '33335501'. Up to 8 digits allowed ", regex='^\\+?1?\\d{8,8}$')])),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '07123456789'. Up to 10 digits allowed.", regex='^\\+?1?\\d{10,10}$')])),
                ('dob', models.DateField(blank=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=None, to='property.Property')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=None, to='unit.Unit')),
            ],
            options={
                'verbose_name': 'tenant',
                'verbose_name_plural': 'tenants',
            },
        ),
    ]
