# Generated by Django 2.2.3 on 2019-07-23 11:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenant', '0001_initial'),
        ('property', '0003_property_completion_year'),
        ('unit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('deposit_amount', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Amount must be entered in the format: '10000'. Up to 20 digits allowed.", regex='^\\+?1?\\d{1,20}$')])),
                ('rent_amount', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Amount must be entered in the format: '10000'. Up to 20 digits allowed.", regex='^\\+?1?\\d{1,20}$')])),
                ('day_to_pay_rent', models.IntegerField(blank=True, null=True)),
                ('rent_payment_type', models.CharField(blank=True, choices=[('DY', 'Days'), ('MN', 'Months'), ('WK', 'Weeks'), ('YR', 'Years')], max_length=10, null=True)),
                ('rent_start_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=None, to='property.Property')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=None, to='tenant.Tenant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=None, to='unit.Unit')),
            ],
            options={
                'verbose_name': 'agreement',
                'verbose_name_plural': 'agreements',
            },
        ),
    ]
