# Generated by Django 2.2.3 on 2019-07-29 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agreement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreement',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='property.Property'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='rent_payment_type',
            field=models.CharField(blank=True, choices=[('MN', 'Months'), ('YR', 'Years')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenant.Tenant'),
        ),
        migrations.AlterField(
            model_name='agreement',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='unit.Unit'),
        ),
    ]
