# Generated by Django 2.2.3 on 2019-07-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0003_property_completion_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('no_of_bed', models.IntegerField(blank=True, null=True)),
                ('no_of_bathroom', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True, null=True)),
                ('property', models.ForeignKey(blank=True, null=True, on_delete=None, to='property.Property')),
            ],
            options={
                'verbose_name': 'unit',
                'verbose_name_plural': 'units',
            },
        ),
    ]
