# Generated by Django 2.2.3 on 2019-07-23 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='property',
        ),
    ]
