# Generated by Django 2.2.3 on 2019-07-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_remove_transaction_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='payer',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='unit',
        ),
    ]
