# Generated by Django 2.2.3 on 2019-07-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenant', '0001_initial'),
        ('transaction', '0004_auto_20190723_1423'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='tenant.Tenant'),
        ),
    ]
