export const GET_ERRORS = "GET_ERRORS";

export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_PROPERTY = "GET_PROPERTY";
export const DELETE_PROPERTY = "DELETE_PROPERTY";
export const ADD_PROPERTY = "ADD_PROPERTY";
export const EDIT_PROPERTY = "EDIT_PROPERTY";

export const GET_AGREEMENT = "GET_AGREEMENT";
export const DELETE_AGREEMENT = "DELETE_AGREEMENT";
export const ADD_AGREEMENT = "ADD_AGREEMENT";

export const GET_TRANSACTION = "GET_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const ADD_TRANSACTION = "ADD_TRANSACTION";

export const GET_TENANT = "GET_TENANT";
export const DELETE_TENANT = "DELETE_TENANT";
export const ADD_TENANT = "ADD_TENANT";

export const GET_UNIT = "GET_UNIT";
export const DELETE_UNIT = "DELETE_UNIT";
export const ADD_UNIT = "ADD_UNIT";
export const UNIT_LOADING = "UNIT_LOADING";
export const EDIT_UNIT = "EDIT_UNIT";

export const EDIT_TRANSACTION = "EDIT_TRANSACTION";

export const EDIT_AGREEMENT = "EDIT_AGREEMENT";
