# Generated by Django 2.2.3 on 2019-07-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='year_of_completion',
        ),
    ]
