# Generated by Django 2.2.3 on 2019-07-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_remove_property_year_of_completion'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='completion_year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
