# Generated by Django 2.2.3 on 2019-07-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0003_property_completion_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_photo',
            field=models.ImageField(blank=True, upload_to='property_photos', verbose_name='property-img'),
        ),
    ]
